### ISSUE TITLE
5.7 and 5.8 syntax error in guide.

### ISSUE THREAD

**Issue by Spartan-196** [launchscout/nku#9]
After adding
     post GET    /posts/:id(.:format)      posts#show
     posts GET    /posts(.:format)      posts #index

from steps 5.7 and 5.8 into my routes.rb file which I initially typed by hand and later copy and pasted because they did not work I am no unable to launch my rails server and preview pages after my box went idle. 
Below is my terminal log. If anyone is up and can provide some insight it would be appreciated.

```
    action@atkinsonj3-70439:~/nku-rails(master*)$ rails server                                                                                                              
    => Booting WEBrick                                                                                                                                                      
    => Rails 4.0.2 application starting in development on http://0.0.0.0:3000                                                                                               
    => Run `rails server -h` for more startup options                                                                                                                       
    => Ctrl-C to shutdown server                                                                                                                                            
    Exiting                                                                                                                                                                 
    /home/action/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load': 
    /home/action/nku-rails/config/routes.rb:5: syntax error, unexpected ':', expecting keyword_end (SyntaxError)                                                                                                                  
    post GET    /posts/:id(.:format)      posts#show                                                                                                                    
                        ^                                                                                                                                               
    /home/action/nku-rails/config/routes.rb:16: syntax error, unexpected ':', expecting keyword_end                                                                  
    #   get 'products/:id' => 'catalog#view'                                                                                                                              
                     ^                                                                                     
    /home/action/nku-rails/config/routes.rb:16: syntax error, unexpected tIDENTIFIER, expecting keyword_end                                                                
    #   get 'products/:id' => 'catalog#view'                                                                                  
```
###### ##Update

there seems to be a problem with :id across my entire environment though I am unsure why as the rake routes come back exactly as it does in the getting started

```
action@atkinsonj3-70439:~/nku-rails(master*)$ rake routes
   Prefix Verb   URI Pattern               Controller#Action                                                                                                             
    posts GET    /posts(.:format)          posts#index                                                                                                                   
          POST   /posts(.:format)          posts#create                                                                                                                  
 new_post GET    /posts/new(.:format)      posts#new                                                                                                                     
edit_post GET    /posts/:id/edit(.:format) posts#edit                                                                                                                    
     post GET    /posts/:id(.:format)      posts#show                                                                                                                    
          PATCH  /posts/:id(.:format)      posts#update                                                                                                                  
          PUT    /posts/:id(.:format)      posts#update                                                                                                                  
          DELETE /posts/:id(.:format)      posts#destroy                                                                                                                 
     root GET    /                         welcome#index
```
###### ## Update 2

I have progressed forward anyways read some of the other documents available and my current routes.rb looks as it does below but the same problem persist, and I have back worked most the steps in the assignment and have yet to narrow the problem. 

```
NkuRails::Application.routes.draw do
  #get "welcome/index"
    resources :posts #Adds REST resources
    GET    /posts/:id(.:format)      posts #show
    GET    /posts/:id(.:format)      posts #index
    DELETE /posts/:id(.:format)      posts#destroy
    root to: 'welcome#index' #Rails Root location to start looking from
end
```
#### Update 3

I have been able to proceeded some to step 6.4 but cannot go past it due to more errors. I will try and work on this some at work tomorrow and keep checking back here
Current error message:

```
action@atkinsonj3-70439:~/nku-rails(master)$ rails generate controller Comments                                                                                          
/home/action/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load': /home/action/nku-rails/config/routes.rb:64: syntax error, unexpected end-of-input, expecting keyword_end (SyntaxError) 
```

**Comment by beisert1** [comment]
I don't think you are supposed to add these lines to any of the files.
"post GET /posts/:id(.:format) posts#show"
"posts GET /posts(.:format) posts #index"

**Comment by Spartan-196** [comment]
If that is the case. These directions are unclear and I messed it all up.
![directions_unclear](https://f.cloud.github.com/assets/1337533/1995084/15a4246a-84fd-11e3-931f-ccd8b2bc0a15.png)

**Comment by jaimerump** [comment]
I remember being confused about that myself. When they show GET/POST/DELETE $url, they're just showing you the default route syntax. You don't actually have to define the routes because those are the Rails conventions, you only have to configure your own routes if you want to do them differently. In the routes file you really only need the resource and root lines, and the rest is implied.

**Comment by Spartan-196** [comment]
I have removed those and I am now able to start the server and can now work through other problems flagged on welcome.html.erb and edit.html.erb

**Comment by cavangrl** [comment]
Hi there,

i just had the same problem and thankfully stumbled upon this site.  I did what you said and it worked.  Thank you thank you
